name: Publish Docker

on:
  push:
    branches:
      - saga
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    strategy:
      matrix:
        sdk_nrf_version:
          - main
          - v2.4
          - v2.3
          - v2.2
          - v2.1
          - v2.0

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: |
          docker build -t nordicplayground/nrfconnect-sdk:${{ matrix.sdk_nrf_version }} \
            --build-arg sdk_nrf_version=${{ matrix.sdk_nrf_version }} \
            .

      - name: Build asset_tracker_v2 application
        run: |
          docker run --rm \
            -v ${PWD}:/workdir/project \
            -w /workdir/nrf/applications/asset_tracker_v2 \
            nordicplayground/nrfconnect-sdk:${{ matrix.sdk_nrf_version }} \
              nrfutil toolchain-manager launch /bin/bash -- -c '\
                west build -b nrf9160dk_nrf9160ns --build-dir /workdir/project/build -- -DEXTRA_CFLAGS="-Werror -Wno-dev"
              '

      - uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: asset_tracker_v2-${{ matrix.sdk_nrf_version }}
          path: |
            build/zephyr/merged.hex
            build/zephyr/app_update.bin

      - name: Ensure nrfjprog works
        run: |
          docker run --rm nordicplayground/nrfconnect-sdk:${{ matrix.sdk_nrf_version }} nrfjprog -v

      - name: Ensure clang-format works
        run: |
          docker run --rm nordicplayground/nrfconnect-sdk:${{ matrix.sdk_nrf_version }} clang-format --version

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: nordicplayground
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish image
        run: |
          docker images
          docker push nordicplayground/nrfconnect-sdk:${{ matrix.sdk_nrf_version }}
